---
apiVersion: batch/v1
kind: Job
metadata:
  name: descheduler-job
  namespace: kube-system
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: descheduler-pod
    spec:
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      priorityClassName: system-cluster-critical
      containers:
        - name: descheduler
<<<<<<< HEAD
          image: ccr.ccs.tencentyun.com/eqxiu/descheduler:v0.19.0
=======
          image: k8s.gcr.io/descheduler/descheduler:v0.20.0
>>>>>>> f54df67d11c730d750eb34c8b585f18cd6029f8e
          volumeMounts:
          - mountPath: /policy-dir
            name: policy-volume
          command:
            - "/bin/descheduler"
          args:
            - "--policy-config-file"
            - "/policy-dir/policy.yaml"
            - "--v"
            - "3"
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
      restartPolicy: "Never"
      serviceAccountName: descheduler-sa
      volumes:
      - name: policy-volume
        configMap:
          name: descheduler-policy-configmap
